vize final
ubselcuk/bai-bai pull request #68
Opened 2021-06-26 20:44 UTC by mactorient

2021-07-05 18:55 UTC, Dines97 commented
Lutfen Pul Requstlerde dunyanin yarisin ekleme. Kontrol etmek zor oluyor. Ve java icin geldim. Baris soyledi javaya gectigini. Ve uzun sure kimse bakmiyorsa Dark Hole de Git Master Race etiketlemekten cekinme

2021-07-05 19:06 UTC, Dines97 commented
![image](https://user-images.githubusercontent.com/19364873/124510760-357fa200-dddd-11eb-959f-db5f9010863a.png)
manyak herif

2021-07-05 20:03 UTC, Dines97 commented
git ile alakali kucuk ders. eyer dosya yi bir yerden bir yere hareket etirceksen, o commite o dosyayla ile yaptigin tek islem hareket ettirme olsun. git dosyayi degil icerigini takip ediyor. boylece dosya hareket ettirildiyse bile takip edebiliyor. ama eyer ayni dosyayi hareket ettirmekle beraber icerigini degistirdiysen bu durumda git bunu takip edemiyor ve git te bir dosya silindi ve bambaska bir dosya eklendi gibi gorunmeye basliyor buna genel olarak takip etmeyi zorlastiriyor. suanda degistirebilicegin bisey yok sonraki defalar icin soyluyorum sadece.

2021-07-05 20:11 UTC, mactorient commented
O kısım dediğin gibi biraz karışık oldu bi kısmını bir ay önce bilgisayarda halletmiş fakat yüklememiştim. Sonra olan oldu 😁

2021-07-05 20:28 UTC, Dines97 requested changes
simdilik kabul etmiyorum senin duzeltmen ve barisin bakmasi gereken yerler var

2021-07-06 19:26 UTC, Dines97 commented
Ya simdilik kabul edicem bu pull requesti, ama bir dahakine bu kadar karisik bir pull request kabul etmem. 1 Pull request 1 odeve denk gelsin. Pull requste sadece duzeltme varsa o zamanda odev ekleme ona. Ve kendim de ogrenmek amacli squash and merge seklinde bunu kabul edicem yani senin 25 commit silinecek onun yerine bir tane commit olacak herseyi temsil eden.

2021-07-06 19:26 UTC, merged