Orta_Algoritma_1-2 22.07.2024
ubselcuk/bai-bai pull request #76
Opened 2024-07-22 13:11 UTC by muriarty1893

Pyhton kullanıyorum. Basit Algoritma bölümünü pas geçiyorum. Linked list taskları bölümünü pas geçiyorum.

2024-07-24 07:22 UTC, ubselcuk commented
3 yıldır kimse buraya pull request atmamıştı, eski kalmış kısımları olabilir. Kodunu review edeceğiz ve hatalı bir durum varsa sana yardımcı olmaya çalışacağız.

2024-07-24 07:25 UTC, muriarty1893 commented
Teşekkürler, zahmet etmenize gerek yok, pull request atarken de bir
beklentim yoktu. Kolay gelsin o7.

24 Tem 2024 Çar 10:22 tarihinde Utku Barış Selçuk ***@***.***>
şunu yazdı:

> 3 yıldır kimse buraya pull request atmamıştı, eski kalmış kısımları
> olabilir. Kodunu review edeceğiz ve hatalı bir durum varsa sana yardımcı
> olmaya çalışacağız.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ubselcuk/bai-bai/pull/76#issuecomment-2247090288>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQP45CZPDO2N6QFVSCQCFF3ZN5I37AVCNFSM6AAAAABLIJQA2SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBXGA4TAMRYHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-25 18:00 UTC, mcandemir commented
Selamlar, PR'ı locale pullayıp test ettim. Kodun çalışmasına bakınca oldukça okay görünüyor bana, fonksiyonlara güzelce de ayırmışsın düzenli bir yapıya sahip. Burada bir ricam olacak;

- 1. modül için `passwords.txt` dosyası kullanılırken 2. modül için de yeni bir dosya oluşturup `passwords_encrypted.txt` diyebilirsin, böylece modüller aynı dosya üzerinde çakışmaz. O şekilde PR daha temiz olur.

Bunun yanı sıra bu yapıyı Class kullanarak da yazabilirsin, bir obje hem encryption hem de decryption görevini üstlenebilir, hem de OOP pratiğin gelişir. Fonksiyonların mantığını gayet iyi kullanıyorsun, Class yapısını da iyi kullanacağına şüphem yok, sana kalmış o yüzden tamamen. Ellerine sağlık.

2024-07-25 18:11 UTC, mcandemir requested changes
Selamlar, PR'ı locale pullayıp test ettim. Kodun çalışmasına bakınca oldukça okay görünüyor bana, fonksiyonlara güzelce de ayırmışsın düzenli bir yapıya sahip. Burada bir ricam olacak sadece, review'a yazdim onu.

Bunun yanı sıra bu yapıyı Class kullanarak da yazabilirsin, bir obje hem encryption hem de decryption görevini üstlenebilir, hem de OOP pratiğin gelişir. Fonksiyonların mantığını gayet iyi kullanıyorsun, Class yapısını da iyi kullanacağına şüphem yok, sana kalmış o yüzden tamamen. Ellerine sağlık.

2024-07-25 18:11 UTC, mcandemir commented on murat_reis/Orta_Algoritma_2.py
> +fname = "passwords.txt"  # Kayıt dosyası adı
1\. modül için `passwords.txt` dosyası kullanılırken 2. modül için de yeni bir dosya oluşturup `passwords_encrypted.txt` diyebilirsin, böylece modüller aynı dosya üzerinde çakışmaz. O şekilde PR daha temiz olur.

2024-07-28 15:29 UTC, mcandemir approved these changes

2024-07-28 15:29 UTC, merged